# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for UDS Diagnostics App
# Targets: Raspberry Pi (armv7l / arm64) - Raspberry Pi OS

import os

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('config.json', '.'),
        ('drivers/config_loader.py', 'drivers'),
        ('drivers/oled_display.py', 'drivers'),
        ('drivers/button_input.py', 'drivers'),
        ('drivers/uds_client.py', 'drivers'),
        ('drivers/transfer_file.py', 'drivers'),
        ('drivers/Parse_handler.py', 'drivers'),
        ('drivers/can_logger.py', 'drivers'),
        ('drivers/report_generator.py', 'drivers'),
        ('drivers/__init__.py', 'drivers'),
    ],
    hiddenimports=[
        'RPi',
        'RPi.GPIO',
        'board',
        'busio',
        'adafruit_ssd1306',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'can',
        'can.interfaces.socketcan',
        'can.io.asc',
        'isotp',
        'udsoncan',
        'udsoncan.client',
        'udsoncan.connections',
        'udsoncan.configs',
        'udsoncan.services',
        'udsoncan.AsciiCodec',
        'drivers',
        'drivers.config_loader',
        'drivers.oled_display',
        'drivers.button_input',
        'drivers.uds_client',
        'drivers.transfer_file',
        'drivers.Parse_handler',
        'drivers.can_logger',
        'drivers.report_generator',
        'csv',
        'json',
        'socket',
        'shutil',
        'logging',
        'subprocess',
        'datetime',
        'collections',
        'html',
        'textwrap',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='uds_diagnostics',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
